package pojo;

// Generated 11 juin 2014 17:16:45 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Adresse generated by hbm2java
 */
@Entity
@Table(name = "adresse", catalog = "mldcorection")
public class Adresse implements java.io.Serializable {

	private char idAdresse;
	private String rue;
	private int num;
	private String ville;
	private long zip;
	private Set<Fournisseur> fournisseurs = new HashSet<Fournisseur>(0);
	private Set<Client> clients = new HashSet<Client>(0);
	private Set<Facture> factures = new HashSet<Facture>(0);

	public Adresse() {
	}

	public Adresse(char idAdresse, String rue, int num, String ville, long zip) {
		this.idAdresse = idAdresse;
		this.rue = rue;
		this.num = num;
		this.ville = ville;
		this.zip = zip;
	}

	public Adresse(char idAdresse, String rue, int num, String ville, long zip,
			Set<Fournisseur> fournisseurs, Set<Client> clients,
			Set<Facture> factures) {
		this.idAdresse = idAdresse;
		this.rue = rue;
		this.num = num;
		this.ville = ville;
		this.zip = zip;
		this.fournisseurs = fournisseurs;
		this.clients = clients;
		this.factures = factures;
	}

	@Id
	@Column(name = "IdAdresse", unique = true, nullable = false, length = 1)
	public char getIdAdresse() {
		return this.idAdresse;
	}

	public void setIdAdresse(char idAdresse) {
		this.idAdresse = idAdresse;
	}

	@Column(name = "rue", nullable = false, length = 100)
	public String getRue() {
		return this.rue;
	}

	public void setRue(String rue) {
		this.rue = rue;
	}

	@Column(name = "num", nullable = false)
	public int getNum() {
		return this.num;
	}

	public void setNum(int num) {
		this.num = num;
	}

	@Column(name = "ville", nullable = false, length = 100)
	public String getVille() {
		return this.ville;
	}

	public void setVille(String ville) {
		this.ville = ville;
	}

	@Column(name = "zip", nullable = false)
	public long getZip() {
		return this.zip;
	}

	public void setZip(long zip) {
		this.zip = zip;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adresse")
	public Set<Fournisseur> getFournisseurs() {
		return this.fournisseurs;
	}

	public void setFournisseurs(Set<Fournisseur> fournisseurs) {
		this.fournisseurs = fournisseurs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adresse")
	public Set<Client> getClients() {
		return this.clients;
	}

	public void setClients(Set<Client> clients) {
		this.clients = clients;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adresse")
	public Set<Facture> getFactures() {
		return this.factures;
	}

	public void setFactures(Set<Facture> factures) {
		this.factures = factures;
	}

}
