package pojo;

// Generated 11 juin 2014 17:16:45 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name = "client", catalog = "mldcorection")
public class Client implements java.io.Serializable {

	private char idClient;
	private Adresse adresse;
	private String nom;
	private String prenom;
	private long telephone;
	private Set<Facture> factures = new HashSet<Facture>(0);

	public Client() {
	}

	public Client(char idClient, Adresse adresse, String nom, String prenom,
			long telephone) {
		this.idClient = idClient;
		this.adresse = adresse;
		this.nom = nom;
		this.prenom = prenom;
		this.telephone = telephone;
	}

	public Client(char idClient, Adresse adresse, String nom, String prenom,
			long telephone, Set<Facture> factures) {
		this.idClient = idClient;
		this.adresse = adresse;
		this.nom = nom;
		this.prenom = prenom;
		this.telephone = telephone;
		this.factures = factures;
	}

	@Id
	@Column(name = "IdClient", unique = true, nullable = false, length = 1)
	public char getIdClient() {
		return this.idClient;
	}

	public void setIdClient(char idClient) {
		this.idClient = idClient;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdAdresse", nullable = false)
	public Adresse getAdresse() {
		return this.adresse;
	}

	public void setAdresse(Adresse adresse) {
		this.adresse = adresse;
	}

	@Column(name = "nom", nullable = false, length = 100)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", nullable = false, length = 100)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "telephone", nullable = false)
	public long getTelephone() {
		return this.telephone;
	}

	public void setTelephone(long telephone) {
		this.telephone = telephone;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "client")
	public Set<Facture> getFactures() {
		return this.factures;
	}

	public void setFactures(Set<Facture> factures) {
		this.factures = factures;
	}

}
