package pojo;

// Generated 11 juin 2014 17:16:45 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Produit generated by hbm2java
 */
@Entity
@Table(name = "produit", catalog = "mldcorection")
public class Produit implements java.io.Serializable {

	private char idProduit;
	private long reference;
	private long prixHtva;
	private long tauxTva;
	private long numSerie;
	private String description;
	private Set<Categorie> categories = new HashSet<Categorie>(0);
	private Set<Typeproduit> typeproduits = new HashSet<Typeproduit>(0);
	private Set<Commande> commandes = new HashSet<Commande>(0);
	private Set<Facture> factures = new HashSet<Facture>(0);

	public Produit() {
	}

	public Produit(char idProduit, long reference, long prixHtva, long tauxTva,
			long numSerie, String description) {
		this.idProduit = idProduit;
		this.reference = reference;
		this.prixHtva = prixHtva;
		this.tauxTva = tauxTva;
		this.numSerie = numSerie;
		this.description = description;
	}

	public Produit(char idProduit, long reference, long prixHtva, long tauxTva,
			long numSerie, String description, Set<Categorie> categories,
			Set<Typeproduit> typeproduits, Set<Commande> commandes,
			Set<Facture> factures) {
		this.idProduit = idProduit;
		this.reference = reference;
		this.prixHtva = prixHtva;
		this.tauxTva = tauxTva;
		this.numSerie = numSerie;
		this.description = description;
		this.categories = categories;
		this.typeproduits = typeproduits;
		this.commandes = commandes;
		this.factures = factures;
	}

	@Id
	@Column(name = "IdProduit", unique = true, nullable = false, length = 1)
	public char getIdProduit() {
		return this.idProduit;
	}

	public void setIdProduit(char idProduit) {
		this.idProduit = idProduit;
	}

	@Column(name = "reference", nullable = false)
	public long getReference() {
		return this.reference;
	}

	public void setReference(long reference) {
		this.reference = reference;
	}

	@Column(name = "prixHTVA", nullable = false)
	public long getPrixHtva() {
		return this.prixHtva;
	}

	public void setPrixHtva(long prixHtva) {
		this.prixHtva = prixHtva;
	}

	@Column(name = "tauxTVA", nullable = false)
	public long getTauxTva() {
		return this.tauxTva;
	}

	public void setTauxTva(long tauxTva) {
		this.tauxTva = tauxTva;
	}

	@Column(name = "numSerie", nullable = false)
	public long getNumSerie() {
		return this.numSerie;
	}

	public void setNumSerie(long numSerie) {
		this.numSerie = numSerie;
	}

	@Column(name = "description", nullable = false, length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "produits")
	public Set<Categorie> getCategories() {
		return this.categories;
	}

	public void setCategories(Set<Categorie> categories) {
		this.categories = categories;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "ajout_d_un_produit", catalog = "mldcorection", joinColumns = { @JoinColumn(name = "IdProduit", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "IdTypeproduit", nullable = false, updatable = false) })
	public Set<Typeproduit> getTypeproduits() {
		return this.typeproduits;
	}

	public void setTypeproduits(Set<Typeproduit> typeproduits) {
		this.typeproduits = typeproduits;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "produits")
	public Set<Commande> getCommandes() {
		return this.commandes;
	}

	public void setCommandes(Set<Commande> commandes) {
		this.commandes = commandes;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "produits")
	public Set<Facture> getFactures() {
		return this.factures;
	}

	public void setFactures(Set<Facture> factures) {
		this.factures = factures;
	}

}
