package pojo;

// Generated 11 juin 2014 17:16:45 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Typeproduit generated by hbm2java
 */
@Entity
@Table(name = "typeproduit", catalog = "mldcorection")
public class Typeproduit implements java.io.Serializable {

	private char idTypeproduit;
	private String type;
	private Set<Produit> produits = new HashSet<Produit>(0);

	public Typeproduit() {
	}

	public Typeproduit(char idTypeproduit, String type) {
		this.idTypeproduit = idTypeproduit;
		this.type = type;
	}

	public Typeproduit(char idTypeproduit, String type, Set<Produit> produits) {
		this.idTypeproduit = idTypeproduit;
		this.type = type;
		this.produits = produits;
	}

	@Id
	@Column(name = "IdTypeproduit", unique = true, nullable = false, length = 1)
	public char getIdTypeproduit() {
		return this.idTypeproduit;
	}

	public void setIdTypeproduit(char idTypeproduit) {
		this.idTypeproduit = idTypeproduit;
	}

	@Column(name = "type", nullable = false, length = 100)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "typeproduits")
	public Set<Produit> getProduits() {
		return this.produits;
	}

	public void setProduits(Set<Produit> produits) {
		this.produits = produits;
	}

}
